config:
  burrito:
    runner:
      image:
        repository: burrito
        tag: DEV_TAG
        pullPolicy: Never
    datastore:
      hostname: "burrito-datastore.burrito-system.svc.cluster.local"
      serviceAccounts:
        - "burrito-system/burrito-runner"
        - "burrito-system/burrito-controllers"
        - "burrito-system/burrito-server"
      storage:
        mock: true
global:
  deployment:
    image:
      repository: burrito
      tag: DEV_TAG
      pullPolicy: Never
tenants:
  - namespace:
      create: true
      name: "burrito-project"
